/**
 * Proper nouns that should keep their original capitalisation even when
 * lowercase mode is on. Add new names here as content grows.
 *
 * Matching rules:
 * - Case-sensitive, exact match.
 * - Word-boundary aware: non-letter characters either side are fine
 *   (so "Sydney" matches inside "Sydney-based" and is preserved as "Sydney",
 *   while "-based" is still lowercased).
 * - Longer entries are matched before shorter ones, so "South Coast" wins
 *   over "Coast" and "Snowy Mountains" wins over "Snowy".
 */
export const properNouns: string[] = [
	// Pronoun
	'I',

	// Personal / identity
	'Matej Groombridge',
	'Matej',
	'Groombridge',

	// Education / work
	'UNSW',
	'Co-op',
	'Atlassian',

	// Tech / brands
	'SvelteKit',
	'Svelte',
	'TypeScript',
	'JavaScript',
	'SCSS',
	'CSS',
	'HTML',
	'Markdown',
	'GitHub',
	'LinkedIn',
	'Instagram',
	'Netlify',
	'Google',
	'Sony',
	'Canon',
	'Samsung',
	'DJI',
	'Galaxy',
	'EOS',
	'SEO',

	// Places — Sydney area
	'Sydney Cricket Ground',
	'Sydney Coastal Walk',
	'Sydney',
	'Vaucluse',
	'La Perouse',
	'Wollongong',

	// Places — NSW / AU regions
	'Snowy Mountains',
	'Snowy Mtns.',
	'Snowies',
	'Lake Tabourie',
	'Central West',
	'South Coast',
	'Gold Coast',
	'Mayfield Gardens',
	'Lost City',
	'Glen Davis',
	'Bathurst',
	'Lithgow',
	'Australia',
	'Australian',

	// Places — Europe
	'Slovenia',
	'Slovenian',
	'Velika Planina',
	'Smarna Gora',
	'Arboretum',
	'Piran',
	'Prague',
	'Czech Republic',
	'Czech',
	'Vienna',
	'Austria',
	'Austrian',
	'Salzburg',
	'Croatia',
	'Croatian',
	'Krk',

	// Months (proper nouns in English)
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
	'Jan',
	'Feb',
	'Mar',
	'Apr',
	'Jun',
	'Jul',
	'Aug',
	'Sep',
	'Sept',
	'Oct',
	'Nov',
	'Dec',

	// Weekdays
	'Monday',
	'Tuesday',
	'Wednesday',
	'Thursday',
	'Friday',
	'Saturday',
	'Sunday',

	// Book authors
	'Greg McKeown',
	'Christopher McDougall',
	'Kapil Gupta',
	'Kevin Kelly',
	'Robin Sharma',
	'Scott Petty',
	'Herman Hesse',
	'Alex Hormozi',
	'Martin Ayers',
	'Kamal Ravikant',
	'Tim Ferriss',
	'Eric Jorgenson',
	'Eckhart Tolle',
	'Thibaut Meurisse',
	'Brother Lawrence',
	'Michael Singer',
	'Mark Manson',
	'Alex & Brett Harris',
	'Derek Sivers',
	'C.S. Lewis',
	'David Deida',
	'Thomas Frank',
	'Lao Tzu',
	'Napoleon Hill',
	'Dan Koe',
	'Kevin Horsley',
	'Vadim Zeland',
	'James Clear',
	'Rolff Potts',
	'Naval Ravikant',

	// Book titles / phrases unique enough to preserve verbatim
	'Essentialism',
	'Born To Run',
	'Atmamun',
	'Excellent Advice for Living',
	'The 5AM Club',
	'5AM Club',
	"What's Life All About?",
	'Siddhartha',
	'$100 Million Leads',
	'Keep the Faith',
	'Love Yourself Like Your Life Depends on It',
	'The 4-Hour Workweek',
	'4-Hour Workweek',
	'The Almanack of Naval Ravikant',
	'The Power of Now',
	'Strategic Mindset',
	'The Practice of the Presence of God',
	'The Surrender Experiment',
	'The Subtle Art of Not Giving A F*ck',
	'Do Hard Things',
	'How To Live',
	'The Screwtape Letters',
	'Dopamine Detox',
	'The Way of the Superior Man',
	'10 Steps to Earning Awesome Grades',
	'Tao Te Ching',
	'Think and Grow Rich',
	'The Art of Focus',
	'Unlimited Memory',
	'Anything You Want',
	'Reality Transurfing',
	'Atomic Habits',
	'Vagabonding'
];
